version: '3.7'

services:
  web:
    container_name: rot-ui-cont
    build:
      context: ui-rot
      dockerfile: Dockerfile.dev
    volumes:
      - './ui-rot:/app'
      - '/app/node_modules'
    ports:
      - 8885:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
